export const SET_LOCATION = 'SET_LOCATION';
export const SET_SEARCH_LOCATION = 'SET_SEARCH_LOCATION';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_HOURLY_FORECAST = 'SET_HOURLY_FORECAST';
