export const CHANGE_FORECAST_SCALE = 'CHANGE_FORECAST_SCALE';
export const CHANGE_TEMP_SCALE = 'CHANGE_TEMP_SCALE';
export const CHANGE_METRIC_SCALE = 'CHANGE_METRIC_SCALE';
export const CHANGE_PRESSURE_SCALE = 'CHANGE_PRESSURE_SCALE';
