export const SET_FAVORITES_CITIES = 'SET_FAVORITES_CITIES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const UPDATE_FAVORITE_CITY = 'UPDATE_FAVORITE_CITY';
