/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zisisbad (https://sketchfab.com/zisisbad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-36ac223837984d9a841f39edabeefa10
title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/scene.gltf");

    useFrame((state) => {
        group.current.rotation.y += 0.001;
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        geometry={nodes.Object_4.geometry}
                        material={materials["Material.001"]}
                    />
                </group>
            </group>
        </group>
    );
};

useGLTF.preload("/scene.gltf");
